### PR TITLE
Logging

### PR DESCRIPTION
**Pull request by AndreiKingsley**

### CODE REVIEW

**Comment by jeinygroove** [comment]
Snippet from logs
Снимок экрана 2021-05-18 в 15 14 32

**Comment by jeinygroove** [comment]
Prometheus
Снимок экрана 2021-05-18 в 15 20 11

**Comment by M0nsteR** [comment]
"You know somethin’, Utivich? I think this just might be my masterpiece." (c)

**Review by M0nsteR — APPROVED** [review]
Congrats, excellent work!

**Pull request merged**
